version: "3.4"

services:
  sqldb:
    build:
      context: ../image-postgres
    restart: "no"
    networks:
      - internal
    ports:
      - 5432:5432
    volumes:
      - ../volumes-dev/sqldb:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Test1234
      POSTGRES_DB: chairman
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  # tooling
  adminer:
    image: adminer
    restart: "no"
    networks:
      - internal
    ports:
      - 8080:8080

networks:
  internal:
    driver: bridge
